sensor:

  # Header Temperatures
  - platform: homeassistant
    entity_id: sensor.dining_room_temperature
    id: dining_room_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "Indoors: %d°C / Outdoors: %d°C"
            args: [ '(int)round(x)', '(int)round(id(outdoor_temperature).state)' ]


  - platform: homeassistant
    entity_id: sensor.porch_outdoor_motion_sensor_1_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "Indoors: %d°C / Outdoors: %d°C"
            args: [ '(int)round(id(dining_room_temperature).state)', '(int)round(x)' ]

  # Office Blind Position
  - platform: homeassistant
    entity_id: cover.office_blind
    id: office_blind_position
    attribute: current_position


